[package]
name = "rustler"
version = "0.1.0"
authors = ["astherath <farceriv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
clap="2.33.3"

[lib]
name = "lines"
path = "src/lines.rs"
